// this module is for reusable functions (ex. decode, read file, navigate webpage)
pub mod files;
pub mod compression;
pub mod commands;
pub mod cipher;
pub mod connection;
pub mod bytes;
pub mod game;
pub mod dates;
pub mod process;
pub mod rpgsave;
pub mod codeberg;
pub mod environment;
pub mod deno;
pub mod hausmaerchen;
pub mod rpgmaker;
pub mod modmaker;
pub mod nemlang;
pub mod olid;